### ISSUE TITLE
Battle.net update

### ISSUE THREAD

**Issue by ali-nz** [atyourservicesire/launchandfixcod#2]
Great script, been using it for a year now. It's been a life saver.

Unfortunately today's battle.net update seems to have broken it's ability to launch wz if bn was not already running.
It still works if bn was already open.

**Comment by devjoda** [comment]
I haven't played this game for a long while. It no longer seems to force high priority for me. 

It appears it is not longer possible to check for successful login on window titles, so I just made a quick and dirty loop that just keeps trying to launch the game. 

You can find the new .bat [here](https://github.com/nooberfrombaldursgate/launchandfixcod/blob/master/modernwarfare2019-new.bat).
